### ISSUE TITLE
Add a description to all instructions

### ISSUE THREAD

**Issue by ooflorent** [mraleph/irhydra#35]
Currently the only instructions with a description are: `Change`, `CheckMaps` and `Deoptimize`.
Adding a description to all instructions (or the commonest) would be a great improvement to understand the IR.

**Comment by mraleph** [comment]
There are many instructions to document and most of them have self
explanatory naming. If you have examples of unclearly named instructions
please post them here.

**Comment by ooflorent** [comment]
Everything related to `Osr`:
* `UnknownOSRValue`
* `OsrEntry`

What is `changes[*]` after `CallWithDescriptor`?

**Comment by mraleph** [comment]
Will add. Here is explanation:

OSR stands for *on stack replacement* a process when on version of the code for a running function is replaced by a different version of the code (e.g. optimized) while the function is still running (is _on the stack_). OSR is used to optimize functions with long running loops while these loops are still running.

`OsrEntry` and `UnknownOSRValue` are HIR instructions that are used to represent OSR entry in the control flow graph (`UnknownOSRValue` evaluates to a value that was in the given place in the environment when OSR happens). 

In general you don't need to concern yourself with semantics of these instructions - they are implementation detail of OSR mechanism. 

`changes[*]` means `changes[everything]` - that is *has arbitrary side effects compiler can't reason about*.
