### ISSUE TITLE
The graph could use a legend of some sort.

### ISSUE THREAD

**Issue by PlNG** [mraleph/irhydra#37]
The graph could use a legend as to what box numbers mean, the box colors mean, box borders mean, arrows mean and arrow colors mean.  A hide and show toggle for the legend also might be useful in keeping it unobtrusive.

**Comment by mraleph** [comment]
![screen shot 2015-01-18 at 6 02 43 pm](https://cloud.githubusercontent.com/assets/131846/5793305/fca456a8-9f3e-11e4-8950-1d0375698553.png)
