### ISSUE TITLE
Concurrent recompilation has been disabled for tracing. with IRHydra 2.0

### ISSUE THREAD

**Issue by kapral18** [mraleph/irhydra#42]
$ d8 --trace-hydrogen --trace-phase=Z --trace-deopt --code-comments --hydrogen-track-positions --redirect-code-traces somefile.js
-> Concurrent recompilation has been disabled for tracing.

Any ideas where I failed? Googling didn't help

**Comment by mraleph** [comment]
This is not a failure - but rather it is expected. V8 disables concurrent recompilation when you pass `--trace-hydrogen`. This should not affect anything. Does something not work?

**Comment by kapral18** [comment]
So when trying to pass a promise implementation code, with actual usage of the promise in one file. It produces nothing but a .d8_history file. Is this behavior sane? Do I need to tweak something in my code to have the actual compiling artifacts produced. The code is here https://gist.github.com/kapral18/4e935490f8dd6922e75c

**Comment by mraleph** [comment]
@kapral18 V8 optimizes only hot parts of your code - if nothing is hot then nothing is optimized. It looks like your code is not long running - you need to warm it up, e.g. by repeating 

    var promise = new Promise(function (resolve) {
        resolve('foo');
    });
    var a;
    promise.then(function(result) {
        a = result;
    });

in a loop few thousands times.

**Comment by mraleph** [comment]
I am closing the issue - as there is nothing to fix in IRHydra for now - but feel free to ask any questions you may have here.
