### ISSUE TITLE
IR of certain deopts cannot be accessed in irhydra2 

### ISSUE THREAD

**Issue by manuel-schiller** [mraleph/irhydra#47]
When I click on any of the red "extend" methods of the following trace, the corresponding IR is not shown but the view still displays the previously selected method:

http://mrale.ph/irhydra/2/#gist:b5a405768d12f49d49e5e3188749de42

**Comment by mraleph** [comment]
Thank you for the report and reproduction! This should now be fixed.

Sorry for somewhat long turn around time - I was on vacation.
