### ISSUE TITLE
certain deopts are not highlighted as such in the detailed method view

### ISSUE THREAD

**Issue by manuel-schiller** [mraleph/irhydra#48]
In the following trace,  some methods contain detopts:

http://mrale.ph/irhydra/2/#gist:cb03646d9db987c3e9fa6baa70d04053

In the overview, those methods are hightlighted in red to indicate this:

![overview](https://cloud.githubusercontent.com/assets/17781478/18631508/af4864de-7e72-11e6-9d43-4a17fcbc2c7a.png)

But in the detailed method view, those deopts are not hightlighted anymore:

![detail](https://cloud.githubusercontent.com/assets/17781478/18631502/aa1f05bc-7e72-11e6-8c56-c7a3321df1de.png)

**Comment by mraleph** [comment]
Thank you for the report and reproduction! This should now be fixed.
