### ISSUE TITLE
Fix License info

### ISSUE THREAD

**Issue by vhf** [mraleph/irhydra#51]
A minor oversight here: https://github.com/mraleph/irhydra/blob/8de3d5fd748c0ecc3cc3669a66d0e05decc38975/COPYING#L190

**Comment by mraleph** [comment]
There is no oversight. This should be read in context, starting at [line 179](https://github.com/mraleph/irhydra/blob/8de3d5fd748c0ecc3cc3669a66d0e05decc38975/COPYING#L179). This is a boilerplate that should be used. "Instantiated" version of this boilerplate can be seen in any `*.dart` file: e.g. https://github.com/mraleph/irhydra/blob/8de3d5fd748c0ecc3cc3669a66d0e05decc38975/irhydra/build.dart#L1-L13, you can see that here `[...]` are replaced with actual values.

**Comment by vhf** [comment]
Ok, thanks for the explanation.

I only spent time in [irhydra.dart](https://github.com/mraleph/irhydra/blob/792460df1e089fa84eabe0dbc300dbfff0d4e84d/irhydra/lib/src/ui/hydra.dart) and didn't check the other `.dart`, sorry for the issue.
