### ISSUE TITLE
enabling turbofan doesn't output hydrogen.cfg

### ISSUE THREAD

**Issue by tusharmath** [mraleph/irhydra#52]
Hi @mraleph following your directions as explained here — http://mrale.ph/irhydra/2/#
I am facing this issue.
**Setup**
```
Node: v7.0.0
V8:   5.4.500.36
----------------
```

**Command**
```
node \
--turbo
--trace-hydrogen \
--trace-phase=Z \
--trace-deopt \
--code-comments \
--hydrogen-track-positions \
--redirect-code-traces \
--redirect-code-traces-to=code.asm \
profile.js
```

**Expected**
Creates `hydrogen.cfg` and `code.asm` files

**Actual**
only `code.asm` file is created.

**Comment by mraleph** [comment]
IRHydra does not support TurboFan (it uses an entirely different IR form). 

You can use [turbolizer](https://github.com/v8/v8/tree/master/tools/turbolizer) to view TF IR. (Though I don't think it supports deoptimization matching similar to IRHydra).

There are no plans to support TurboFan in IRHydra.

**Comment by tusharmath** [comment]
thanks!
