### ISSUE TITLE
Splice source into IR (eye icon) no longer works

### ISSUE THREAD

**Issue by krisselden** [mraleph/irhydra#55]
You can reproduce this with the hydrogen.cfg and code.asm files in /irhydra/web/demos/v8

**Comment by krisselden** [comment]
Just confirmed that this is working on https://github.com/mraleph/irhydra/commit/dd523dcded37a61415d9707430b68fda741a5361

![image](https://cloud.githubusercontent.com/assets/61024/21920771/2c00c1ce-d918-11e6-9650-b7bf0fdf8a02.png)

**Comment by krisselden** [comment]
This feature though didn't require disassembly before, it worked with Chrome release, but if you default that only if there is disassembly it requires a custom build.  Do you mind reopening?

**Comment by mraleph** [comment]
@krisselden I reworked the fix. Now it should work even if there is no disassembly. 

(Unfortunately TurboFan deoptimization mapping does require disassembly).
