### ISSUE TITLE
New v8 engine (ignition+turbofan)

### ISSUE THREAD

**Issue by jpambrun** [mraleph/irhydra#59]
Is this expected to work with the newly released v8 engine? If not, are there any alternative.

**Comment by mraleph** [comment]
Depends on which IRHydra features you need. 

You can load scheduled TurboFan CFG into IRHydra (replace `--trace-hydrogen` with `--trace-turbo` and load `turbo.cfg` instead `hydrogen.cfg`). However features like deopt mapping work only partially (e.g. you need a built of V8 with disassembler).

**Comment by jpambrun** [comment]
That's a bummer. I used to use it all the time with chrome. Now I am sad :(.

Thanks for the quick response.
